$("#kastroplayer").kasunaradio({
  userinterface: "big",
  backgroundcolor: "transparent",
  fontcolor: "#ffffff",
  hightlightcolor: "#fa225b",
  fontname: "Saira Condensed",
  googlefont: "Saira+Condensed:wght@100",
  fontratio: "0.5",
  radioname: "Desafio del Sur",
  scroll: "false",
  coverimage: "https://i.imgur.com/TSc5ws2.gif",
  usevisualizer: "fake",
  coverstyle: "animated",
  visualizertype: "9",
  multicolorvisualizer: "true",
    color1: "#f6f6f6",
    color2: "#323edd",
    color3: "#fc5404",
    color4: "#fa225b",
  itunestoken: "1000lIPN",
  metadatatechnic: "",
  ownmetadataurl: "",
  streamurl: "https://stream.zeno.fm/ddqxfkh63hhvv",
  streamtype: "radiozeno",
  icecastmountpoint: "/radio.mp3",
  radionomyid: "",
  radionomyapikey: "",
  radiozenoid: "ddqxfkh63hhvv",
  radiojarid: "",
  radiocoid: "",
  shoutcastpath: "/stream",
  shoutcastid: "1",
  streamsuffix: "",
  metadatainterval: "5000",
  volume: "50",
  debug: "false",
  usestreamcorsproxy: "true", 
  corsproxy: "",
  autoplay:"true",
    });
