$("#kastroplayer").kasradio({
userinterface: "big",
backgroundcolor: "transparent",
themecolor: "#fa225b", 
themefontcolor: "#ffffff", 
startvolume: "50", 
scroll: "false", 
useanalyzer: "real", 
analyzertype: "3", 
radioname: "Desafio del Sur",
usecover: "true",
radiocover: "https://i.imgur.com/TSc5ws2.gif",
streamtype: "zenoradio",
streamurl: "https://stream.zeno.fm/ddqxfkh63hhvv.aac",
zenoid: "ddqxfkh63hhvv",
usestreamcorsproxy: "true",
corsproxy: "",  
autoplay: "true",
songinformationinterval: "5000", 
});
