$("#kastroplayer").kasradio({
userinterface: "big",
backgroundcolor: "transparent",
themecolor: "#FF0000", 
themefontcolor: "#ffffff", 
startvolume: "50", 
scroll: "true", 
useanalyzer: "real", 
analyzertype: "4", 
radioname: "Perla Negra",
usecover: "true",
radiocover: "https://i.imgur.com/TSc5ws2.gif",
streamtype: "zenoradio",
streamurl: "https://stream.zeno.fm/emertvc73mruv.aac",
zenoid: "emertvc73mruv",
usestreamcorsproxy: "true",
corsproxy: "",  
autoplay: "true",
songinformationinterval: "5000", 
});
